name: 'Wait For Check'
description: 'Wait for another GitHub check to complete'
author: 'Fountainhead Technologies Ltd.'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  checkName:
    description: 'The name of the GitHub check to wait for. For example, `build` or `deploy`.'
    required: true
  token:
    description: 'The GitHub token to override GITHUB_TOKEN if needed.'
    default: ${{ secrets.GITHUB_TOKEN }}
  ref:
    description: 'The Git ref of the commit you want to poll for a passing check.'
  repo:
    description: 'The name of the GitHub repository you want to poll for a passing check.'
  owner:
    description: 'The owner of the GitHub repository you want to poll for a passing check.'
  timeoutSeconds:
    description: 'The number of seconds to wait for the check to complete.'
  intervalSeconds:
    description: 'The number of seconds to wait before each poll of the GitHub API.'
runs:
  using: 'node16'
  main: 'dist/index.js'
